---
title: IX Congreso Venezolano de Ecología
date: 21 noviembre 2011
categories: 
 - Venezuela
 - Congreso
 - Nacional
 - Coautor
---
# CVE IX 2011

IX Congreso Venezolano de Ecología. Margarita, 21-25 noviembre 2011


## Enlaces 

 - [Programa](https://svecologia.org/wp-content/uploads/2020/12/IX-CVE-Porlamar-2011-PROGRAMA.pdf)
- [Libro de resúmenes](https://svecologia.org/wp-content/uploads/2020/12/IX-CVE-Porlamar-2011-RESUMENES.pdf) 

## Presentación y productos relacionados

### ES9 Cambios en la Dinámica del carbono y la actividad microbiana del suelo en respuesta a la invasión por _Kalanchoe daigremontiana_ en el Parque Nacional Cerro Saroche 

Benzo, Diana(1); Herrera, Ileana(1); Chacón, Noemí(1); Ferrer-París, José R.(2); Flores, Saúl(1); García, Belkis(1) y Martínez, José(3) 

(1)Laboratorio de Ecología de Suelos. Centro de Ecología. Instituto Venezolano de Investigaciones Científicas. Caracas, Venezuela. 

(2)Centro de Estudios Botánicos y Agroforestales. Instituto Venezolano de Investigaciones Científicas. Maracaibo, Venezuela. 

(3)Postgrado en Ecología. Facultad de Ciencias. Universidad Central de Venezuela. 

> El reemplazo de plantas nativas por plantas exóticas puede modificar el ciclaje de nutrientes en el suelo, conducido principalmente por cambios en la comunidad y actividad microbiana. a pesar de que las plantas exóticas invasoras están en casi todos los ecosistemas terrestres, las zonas áridas parecen ser los hábitats menos invadidos, pero particularmente vulnerables. La invasión por pocas especies de plantas podría modificar este ecosistema, inhibiendo el establecimiento de especies nativas. El Parque Nacional Cerro Saroche, ubicado al noroeste de Venezuela es una de las pocas áreas protegidas que incluyen ecosistemas áridos en el Neotrópico. En esta zona K. daigremontiana cubre una amplia área y ha sido introducida hace más de 50 años. Tomando en cuenta lo anteriormente mencionado, este estudio esperaría que la invasión por K. daigremontiana en las zonas semi-áridas neotropicales pudiera modificar la dinámica del carbono y la actividad microbiana en el suelo. Con este fin, se recolectaron muestras de suelo en el «Cerro Saroche» bajo un sitio invadido por K. daigremontiana (KD) y bajo tres sitios no invadidos: matorrales nativos (Ma), árboles nativos de leguminosas (LE), y el área abierta (aa) sin vegetación. Se determinaron en las muestras de suelo propiedades fisicoquímicas (pH, CO, textura y humedad), biológicas (carbono microbiano y respiración) y bioquímicas (actividad de la deshidrogenasa, glucosidasa y la hidrólisis del diacetato de fluoresceina. Los resultados mostraron que las propiedades bioquímicas en KD no difieren con los sitios Ma y aa. Los mayores valores de humedad, CO, contenido de arcilla y respiración se observaron en KD. De igual manera los datos reflejan una tendencia de mayores valores de carbono microbiano en este sitio. En conjunto, los resultados indican que la invasión por K. daigremontiana puede modificar la dinámica del carbono en el suelo, mejorando los recursos y las condiciones de hábitat que favorecen su establecimiento. Palabras clave: carbono orgánico del suelo, plantas invasoras, propiedades biológicas y bioquímicas del suelo, zonas áridas.

Relacionado con nuestra publicación [@Herrera2018b].