project:
  type: website
  output-dir: docs
  resources: 
    - "lgrs/img/"
    - "img/"

execute:
  freeze: auto

website:
  title: "./jrfep/ mi mundo"
  repo-url: https://github.com/jrfep/mimundo
  
  navbar:
    title: "J.R. Ferrer-Paris"
    href: https://jrfep.github.io/esp/
    type: inverse
    left:
      - text: "Lugares"
        icon: map
        href: lgrs-list.qmd
      - text: "Eventos científicos"
        icon: people
        href: evnt-list.qmd
    right:
      - text: "How to..."
        icon: question
        menu:
          - text: "(re-)create this site"
            href: how2/how-to-site.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true
lang: es 