---
title: Bogotá
categories:
 - Colombia
 - Congresos
 - Familia
---

Para mis padres fue un hogar durante 10 años. De visita en varias oportunidades, Bogotá nos recibió cuando buscabamos camino. Fue nuestro puente entre Venezuela y Australia.


```{r}
slc <- c("¡Chócala!","Gael en el tren","ArtBo")
```


```{r}
library(pixture)
library(dplyr)
here::i_am("lgrs/Melbourne.qmd")
source(here::here("inc", "functions.R"))
```

```{r}
#| output: asis

photos <- filter_flickr_photo(find = slc) |>
    pull_flickr_paths_captions(howmany = 1, preview = TRUE)

cat(sprintf("<center>\n%s\n<br/>\n%s<br/></center>", 
         photos$paths, photos$captions))
```


## Galería de fotos


```{r}
photos <- filter_flickr_photo(seleccion = slc) |>
    pull_flickr_paths_captions()

pixgallery(photos$paths, caption=photos$captions)
```

<blockquote class="imgur-embed-pub" lang="en" data-id="IsKcZNg"><a href="https://imgur.com/IsKcZNg">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>


```{r}
#| output: asis

slc <- "Bogot"
alb <- "Visita a Colombia - Oct 2024"

```



```{r}
gphotos <- filter_ggl_photo(description = slc, 
  album_name = alb) |>
  pull_ggle_paths_captions()
pixgallery(gphotos$paths, caption=gphotos$captions)
```


## Observaciones en iNaturalist


```{r}
#| label: inat
slc <- c("Bogota|Bogotá")
inat_photos <- filter_inat_photo(place=slc) 

if (nrow(inat_photos)>0) {
  inat_photos <- pull_inat_paths_captions(inat_photos,howmany=18)
  pixgallery(inat_photos$paths, caption=inat_photos$captions)
}
```

