---
title: Campeche y Edzná
categories:
 - Mexico
 - Visita
 - Sitios arqueológicos
execute: 
 echo: false
---

Visitamos la ciudad de Campeche para poder visitar el sitio arqueológico de [Edzná](https://es.wikipedia.org/wiki/Edzn%C3%A1).



```{r}
library(pixture)
library(dplyr)
here::i_am("lgrs/Campeche.qmd")
source(here::here("inc", "functions.R"))
```


```{r}
#| output: asis

slc <- c("Campeche|Edzná|Edzna")

gphotos <- filter_ggl_photo(description = slc, 
  album_name = "Lugares - México") |>
  pull_ggle_paths_captions(howmany = 1, preview=TRUE)

htmlcode <- "<center>\n%s\n<br/>\n%s<br/></center>"

show_photo <- sprintf(htmlcode, gphotos$paths, gphotos$captions)
cat(show_photo)
```


## Galería de fotos

```{r}
gphotos <- filter_ggl_photo(description = slc, 
  album_name = "Lugares - México") |>
  pull_ggle_paths_captions()
pixgallery(gphotos$paths, caption=gphotos$captions)
```


## Observaciones en `iNaturalist`

```{r}
inat_photos <- filter_inat_photo(place=slc) |>
  pull_inat_paths_captions(howmany=18)

pixgallery(inat_photos$paths, caption=inat_photos$captions)

```
