---
title: Guarenas
categories:
 - Venezuela
 - Familia
 - Ada
---


```{r}

slc <- c("Full color", "Panorámica Ciudad Casarapa", "gottlos - der Hundertwassersalbtraum")

```


```{r}
library(pixture)
library(dplyr)
here::i_am("lgrs/Guarenas.qmd")
source(here::here("inc", "functions.R"))
```

```{r}
#| output: asis

photos <- filter_flickr_photo(find = slc) |>
    pull_flickr_paths_captions(howmany = 1, preview = TRUE)

cat(sprintf("<center>\n%s\n<br/>\n%s<br/></center>", 
         photos$paths, photos$captions))
```


## Galería de fotos

```{r}
photos <- filter_flickr_photo(seleccion = slc) |>
    pull_flickr_paths_captions()

pixgallery(photos$paths, caption=photos$captions)
```


## Observaciones en iNaturalist


```{r}
#| label: inat
slc <- c("Guarenas|Casarapa")
inat_photos <- filter_inat_photo(place = slc) 

if (nrow(inat_photos) > 0) {
  inat_photos <- inat_photos |>
    pull_inat_paths_captions(howmany = 18)

  pixgallery(inat_photos$paths, caption=inat_photos$captions)  
}
```

