---
title: Sydney
categories:
 - Australia
 - Familia
editor_options: 
  chunk_output_type: console
---


```{r}
library(pixture)
library(dplyr)
here::i_am("lgrs/Sydney.qmd")
source(here::here("inc", "functions.R"))
```


```{r}
#| output: asis

photos <- filter_flickr_photo(find = c("Sydney")) |>
    pull_flickr_paths_captions(howmany = 1, preview = TRUE)

cat(sprintf("<center>\n%s\n<br/>\n%s<br/></center>", 
         photos$paths, photos$captions))
```


## Galería de fotos

```{r}

photos <- filter_flickr_photo(find = c("Sydney")) |>
    pull_flickr_paths_captions()

pixgallery(photos$paths, caption=photos$captions)

```

<blockquote class="imgur-embed-pub" lang="en" data-id="AJYSnM6"  ><a href="//imgur.com/AJYSnM6">Colourful rockpool</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>


## Observaciones en iNaturalist


```{r}

inat_photos <- filter_inat_photo(place="Sydney") |>
  pull_inat_paths_captions(howmany=18)

pixgallery(inat_photos$paths, caption=inat_photos$captions)
```

