---
title: Villahermosa
categories:
 - Mexico
 - Familia
 - Sitios arqueológicos
 - Ada
execute: 
 echo: false
---

Después de la conferencia en [Oaxaca](/lgrs/Oaxaca.qmd) pasamos por Villahermosa para visitar a mi papá que estaba trabajando en esa época en esta ciudad.

Visitamos el Parque Museo de la Venta y [Kolem Jaa'](https://kolemjaa.com/).

En este viaje también fuimos a [Campeche](/lgrs/Campeche.qmd) y visitamos [Palenque](/lgrs/Palenque.qmd).

```{r}
library(pixture)
library(dplyr)
here::i_am("lgrs/Villahermosa.qmd")
source(here::here("inc", "functions.R"))
```


```{r}
#| output: asis

gphotos <- filter_ggl_photo(description = "Villahermosa|La Venta|Tacotalpa", 
  album_name = "Lugares - México") |>
  pull_ggle_paths_captions(howmany = 1, preview=TRUE)

htmlcode <- "<center>\n%s\n<br/>\n%s<br/></center>"

show_photo <- sprintf(htmlcode, gphotos$paths, gphotos$captions)
cat(show_photo)
```


## Galería de fotos

```{r}
gphotos <- filter_ggl_photo(description = "Villahermosa|La Venta|Tacotalpa", 
  album_name = "Lugares - México") |>
  pull_ggle_paths_captions()
pixgallery(gphotos$paths, caption=gphotos$captions)
```


## Observaciones en `iNaturalist`

```{r}
slc <- c("Villahermosa|La Venta|Tacotalpa")
```


```{r}
#| label: inat
slc <- c("Guarenas|Casarapa")
inat_photos <- filter_inat_photo(place = slc) 

if (nrow(inat_photos) > 0) {
  inat_photos <- inat_photos |>
    pull_inat_paths_captions(howmany = 18)

  pixgallery(inat_photos$paths, caption=inat_photos$captions)  
}
```
